Name:           ros-hydro-tf2-kdl
Version:        0.4.12
Release:        0%{?dist}
Summary:        ROS tf2_kdl package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/tf2
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       ros-hydro-orocos-kdl
Requires:       ros-hydro-tf2
Requires:       ros-hydro-tf2-ros
BuildRequires:  eigen3-devel
BuildRequires:  ros-hydro-catkin >= 0.5.68
BuildRequires:  ros-hydro-orocos-kdl
BuildRequires:  ros-hydro-rostest
BuildRequires:  ros-hydro-tf2
BuildRequires:  ros-hydro-tf2-ros

%description
KDL binding for tf2

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Sep 18 2014 Tully Foote <tfoote@osrfoundation.org> - 0.4.12-0
- Autogenerated by Bloom

