Name:           ros-jade-tf2-eigen
Version:        0.5.16
Release:        0%{?dist}
Summary:        ROS tf2_eigen package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-tf2
BuildRequires:  eigen3-devel
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cmake-modules
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-tf2

%description
tf2_eigen

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Sat Jul 15 2017 Koji Terada <terakoji@gmail.com> - 0.5.16-0
- Autogenerated by Bloom

* Tue Jan 24 2017 Koji Terada <terakoji@gmail.com> - 0.5.15-0
- Autogenerated by Bloom

* Mon Jan 16 2017 Koji Terada <terakoji@gmail.com> - 0.5.14-0
- Autogenerated by Bloom

* Fri Mar 04 2016 Koji Terada <terakoji@gmail.com> - 0.5.13-0
- Autogenerated by Bloom

* Wed Aug 05 2015 Koji Terada <terakoji@gmail.com> - 0.5.12-0
- Autogenerated by Bloom

* Wed Apr 22 2015 Koji Terada <terakoji@gmail.com> - 0.5.11-0
- Autogenerated by Bloom

* Tue Apr 21 2015 Koji Terada <terakoji@gmail.com> - 0.5.10-0
- Autogenerated by Bloom

